M48
; DRILL file KiCad 10.0.2 date 2026-08-14T13:53:31
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-14T13:53:31+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X157.19Y-90.855
X162.97Y-90.855
T2
X133.33Y-89.0
X133.33Y-155.0
X186.67Y-89.0
X186.67Y-155.0
M30
