M48
; DRILL file KiCad 10.0.2 date 2026-08-17T14:37:22
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-17T14:37:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X46.8Y-78.8
X46.8Y-116.9
X123.0Y-78.8
X123.0Y-116.9
X224.6Y-78.8
X224.6Y-116.9
M30
